name: starz

on:
  workflow_dispatch:
  schedule: 
   # Run every Tuesday at 0 UTC
    - cron: '0 0 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.8'
    - name: Run discovered weekly
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        python starz.py
